import sqlite3


def insert_video(video: dict, cursor) -> bool:
    """Add a video to the database."""
    try:
        query = """
            INSERT INTO Video
            (video_id, creator_id, views, likes)
            VALUES (?, ?, ?, ?);
        """

        cursor.execute(
            query,
            (
                video["video_id"],
                video["creator_id"],
                video["views"],
                video["likes"],
            )
        )

        return True

    except (sqlite3.Error, OSError) as error:
        print(error)
        return False


def get_video(video_id: str, cursor) -> dict | None:
    """Return the video of specified id from the database.

    Returns the video, an EMPTY dictionary if no video has this id, or None
    if the query to the database failed.
    """
    try:
        query = """
            SELECT *
            FROM Video
            WHERE video_id = ?;
        """

        cursor.execute(query, (video_id,))
        video = cursor.fetchone()

        if video is None:
            return {}

        return dict(video)

    except (sqlite3.Error, OSError) as error:
        print(error)
        return None


def get_videos(cursor) -> list[dict] | None:
    """Return all videos from the database, or None if the query failed."""
    try:
        query = """
            SELECT *
            FROM Video;
        """

        cursor.execute(query)
        videos = cursor.fetchall()

        return [dict(video) for video in videos]

    except (sqlite3.Error, OSError) as error:
        print(error)
        return None


def get_video_orders_count(video_id: str, cursor) -> int | None:
    """Return the number of orders triggered by a video (0 if there is none).

    Returns None if the query to the database failed.
    """
    try:
        query = """
            SELECT COUNT(*)
            FROM "Order"
            WHERE video_id = ?;
        """

        cursor.execute(query, (video_id,))
        result = cursor.fetchone()

        return int(result[0])

    except (sqlite3.Error, OSError) as error:
        print(error)
        return None


def get_best_videos(n: int, cursor) -> list[dict] | None:
    """Return the n videos with the highest net revenue.

    The net revenue of a video is what it sold (the refunded orders do not
    count) minus what the brand spent to push it. Each row also holds the
    name of the creator of the video.

    Returns None if the query to the database failed.
    """
    try:
        query = """
            SELECT Video.*, Creator.name
            FROM Video
            JOIN Creator
                ON Video.creator_id = Creator.creator_id;
        """

        cursor.execute(query)
        videos = cursor.fetchall()

        videos_list = []

        for video in videos:
            video_info = dict(video)

            # Revenue generated by the video
            query = """
                SELECT SUM(Contains.quantity * Contains.final_price)
                FROM "Order"
                JOIN Contains
                    ON "Order".order_id = Contains.order_id
                WHERE "Order".video_id = ?
                AND "Order".refunded = 0;
            """

            cursor.execute(query, (video["video_id"],))
            result = cursor.fetchone()

            sales = 0.0

            if result[0] is not None:
                sales = float(result[0])

            # Money spent promoting the video
            query = """
                SELECT SUM(amount)
                FROM Spend
                WHERE video_id = ?;
            """

            cursor.execute(query, (video["video_id"],))
            result = cursor.fetchone()

            spend = 0.0

            if result[0] is not None:
                spend = float(result[0])

            video_info["net_revenue"] = sales - spend

            videos_list.append(video_info)

        videos_list.sort(
            key=lambda video: video["net_revenue"],
            reverse=True
        )

        return videos_list[:n]

    except (sqlite3.Error, OSError) as error:
        print(error)
        return None